### ISSUE TITLE
Error in the example javascript

### ISSUE THREAD

**Issue by sabas1080** [intel-iot-devkit/aws-iot-intel#7]
Hi I have the next error in javascript 

Intel Edison

```
root@edison:~# node Edison-JS-Sample.js                                         
                                                                                
/home/root/Edison-JS-Sample.js:81                                               
const thingShadows = thingShadow({                                              
                     ^                                                          
TypeError: object is not a function                                             
    at update_state (/home/root/Edison-JS-Sample.js:81:22)                      
    at Object.<anonymous> (/home/root/Edison-JS-Sample.js:75:1)                 
    at Module._compile (module.js:456:26)                                       
    at Object.Module._extensions..js (module.js:474:10)                         
    at Module.load (module.js:356:32)                                           
    at Function.Module._load (module.js:312:12)                                 
    at Function.Module.runMain (module.js:497:10)                               
    at startup (node.js:119:16)                                                 
    at node.js:935:3 
```

Thanks

**Comment by coreyc** [comment]
@sabas1080 if you didn't figure this out yet, is the path in your module require right?  

on the line where it says: 
const thingShadow = require('./thing');

you need to point to the thing directory of the aws-iot-device-sdk
